# Generated by Django 2.2.6 on 2019-10-21 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_readnum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='readed_num',
        ),
    ]
